Update for recent changes to other repos (#13)
* Change codeowners to explicitly disown stuff.

* Remove dependabot PR limits

* Update deny.toml advisories

* Remove cargo-audit (GH does this for us)

* Add crev, TODOs, reformat deny stage.

* Fix issues in own dependabot config.

* Add QoL actions

* Add initial CODEOWNERS.

diff --git a/rust/repo/{{ cookiecutter.repo_name }}/.github/workflows/ci.yaml b/rust/repo/{{ cookiecutter.repo_name }}/.github/workflows/ci.yaml
--- a/rust/repo/{{ cookiecutter.repo_name }}/.github/workflows/ci.yaml
+++ b/rust/repo/{{ cookiecutter.repo_name }}/.github/workflows/ci.yaml
@@ -21,6 +21,7 @@ jobs:
           components: rustfmt
       - uses: r7kamura/rust-problem-matchers@v1
       - run: cargo fmt --all -- --check
+      # TODO: Fix automatically
 
   markdown-lint:
     runs-on: ubuntu-22.04
@@ -30,6 +31,76 @@ jobs:
       - uses: DavidAnson/markdownlint-cli2-action@v9
         with:
           globs: "**/*.md"
+      # TODO: Fix automatically
+
+  crev:
+    runs-on: ubuntu-22.04
+    needs:
+      - "rustfmt"
+      - "markdown-lint"
+    # Override errors here, eventually we'd like to start failing PRs based on this
+    continue-on-error: true
+    permissions:
+      pull-requests: write
+    steps:
+      - uses: actions/checkout@v3
+      - uses: dtolnay/rust-toolchain@stable
+      - uses: actions/cache@v3
+        continue-on-error: false
+        with:
+          path: |
+            Cargo.lock
+            ~/.cargo/bin/
+            ~/.cargo/registry/index/
+            ~/.cargo/registry/cache/
+            ~/.cargo/git/db/
+          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
+          restore-keys: ${{ runner.os }}-cargo-
+      - run: cargo crev trust --level high --no-commit https://github.com/mobilecoinfoundation/crev-proofs
+      - name: Run Cargo Crev
+        id: cargo-crev
+        run: |
+          set +e
+          export MARKER=$RANDOM
+          echo "UNREVIEWED_DEPENDENCIES<<EOF${MARKER}" >> $GITHUB_OUTPUT
+          # GH does not like colors in crev output
+          export TERM=xterm-mono
+          # - Get a TSV-formatted table of dependencies without recorded reviews
+          # - Skip any "local" dependencies
+          # - Convert the table to GHF markdown
+          # - Sort descending by the "LoC" value (first column preceeds first pipe)
+
+          cargo crev crate verify \
+              --for-id vMr-9g5KzKQLsCpkp1tc8o7AR6a0OptjOICjf7NMyHE \
+              --show-all \
+              --skip-indirect \
+              --skip-verified \
+              --skip-known-owners \
+              --trust medium \
+              --thoroughness medium \
+              --understanding medium \
+              --redundancy 2 | \
+            grep -v '^local ' | \
+            awk '{printf("| %s | %s | %s | %s | %s | %s | %s |\n", $14, $15, $2, $10, $11, $12, $13)}' | \
+            sort -t\| -n -k5 | \
+            tee /dev/stderr >> $GITHUB_OUTPUT
+          STATUS=$?
+          echo "EOF${MARKER}" >> $GITHUB_OUTPUT
+
+          set -e
+
+          # TODO: Once we're ready to start failing PRs for lack of dependency reviews
+          # exit $STATUS 
+          exit 0
+        shell: bash
+      - uses: mshick/add-pr-comment@v2
+        with:
+          message: |
+            #### :x: Unreviewed dependencies found
+            
+            | Crate | Version | Reviews (N/2) | LoC | Left-Pad Index | Geiger | Flags |
+            | ----- | ------- | ------------- | --- | -------------- | ------ | ----- |
+            ${{ steps.cargo-crev.outputs.UNREVIEWED_DEPENDENCIES }}
 
   deny:
     runs-on: ubuntu-22.04
@@ -41,13 +112,13 @@ jobs:
         checks:
           - advisories
           - bans licenses sources
-    # Prevent sudden announcement of a new advisory from failing ci:
-    continue-on-error: ${{ matrix.checks == 'advisories' }}
+      fail-fast: false
     steps:
-    - uses: actions/checkout@v2
-    - uses: EmbarkStudios/cargo-deny-action@v1
-      with:
-        command: check ${{ matrix.checks }}
+      - uses: actions/checkout@v2
+      - uses: dtolnay/rust-toolchain@stable
+      - uses: EmbarkStudios/cargo-deny-action@v1
+        with:
+          command: check ${{ matrix.checks }}
 
   sort:
     runs-on: ubuntu-22.04
@@ -59,6 +130,7 @@ jobs:
       - uses: dtolnay/rust-toolchain@stable
       - run: cargo install cargo-sort
       - run: cargo sort --workspace --check >/dev/null
+      # TODO: Fix automatically
 
   clippy:
     runs-on: ubuntu-22.04
@@ -70,8 +142,7 @@ jobs:
         rust:
           - stable
           - beta
-    # Prevent beta clippy warnings from causing CI failure
-    continue-on-error: ${{ matrix.rust == 'beta' }}
+      fail-fast: false
     steps:
       - uses: actions/checkout@v2
       - uses: dtolnay/rust-toolchain@master
@@ -80,6 +151,7 @@ jobs:
           components: clippy
       - uses: r7kamura/rust-problem-matchers@v1
       - run: cargo +${{ matrix.rust }} clippy --all --all-features -- -D warnings
+      # TODO: Fix automatically, or post GH-suggestions comments
 
   build:
     runs-on: ubuntu-22.04
